server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource         # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://114.116.46.58:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Zxl5201314@

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.rise.springCloud.entities   # 所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001  #微服务名
    prefer-ip-address: true  #ip地址显示
    #客户端向服务端发送心跳的时间间隔，单位S，默认30
    lease-renewal-interval-in-seconds: 30
    #服务端在收到最后一次心跳包后等待的时间上限，单位s，默认90
    lease-expiration-duration-in-seconds: 90